[project]
name = "FinanceHub"
version = "0.1.0"
description = "FinanceHub API"
requires-python = ">=3.11"
dependencies = [
    "flask-swagger-ui>=5.21.0",
    "flask>=3.1.1",
    "flask-cors>=6.0.1",
    "marshmallow>=4.0.0",
    "python-dateutil>=2.9.0.post0",
]
